name: EconomyProperty
main: onebone\economyproperty\EconomyProperty
version: "2.0.4"
author: onebone
api: [1.12.0]
depend:
- EconomyLand
- EconomyAPI
permissions:
 economyproperty.*:
  description: Includes all permissions related to EconomyProperty
  default: op
  children:
   economyproperty.property.*:
    description: Includes all permission related to property area
    default: op
    children:
     economyproperty.property.modify:
      description: Allows player to modify property area
      default: op
     economyproperty.property.remove:
      description: Allows player to remove property
      default: op
   economyproperty.command.property:
    description: Allows player to use property command
    default: op
